### ISSUE TITLE
Margens

### ISSUE THREAD

**Issue by ataias** [zaghetto/freneticintelgalileo#1]
Modifiquei as margens no arquivo template da Springer. Verifiquem se agora está bom. Parece ter alguns acentos ainda esquisitos no documento.

**Comment by zaghetto** [comment]
Ataías, atualizei o seu Galileo.
Abraço,
Zaghetto.
Em 16/09/2015 18:50, "Ataias Pereira Reis" <notifications@github.com>
escreveu:

**Comment by ataias** [comment]
=)
